project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "DK"
  site-url: "https://mariecurie.com"
  navbar:
    background: "#536878"
    left:
      - href: blog/index.qmd
        text: Web Logs
      - href: publications/index.qmd
        text: Future Publications
      - href: software/index.qmd
        text: Lessons from Work
      - href: talks/index.qmd
        text: Talks
      - href: teaching/index.qmd
        text: Learning
      - href: about/index.qmd
        text: Of My Soul
  page-footer:
    left: "All Rights Reserved"
    right:
      - icon: github
        href: https://github.com/mariecurie
      - icon: twitter
        href: https://twitter.com/mariecurie
    background: "#536878"

date-format: "D MMMM YYYY"

format:
  html:
    theme: tango
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html
